// <auto-generated />
using ApiStands.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiStands.Migrations
{
    [DbContext(typeof(DBStandsContext))]
    [Migration("20240913124704_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiStands.Models.Stand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parte")
                        .HasColumnType("int");

                    b.Property<string>("Portador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Habilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Forma = "Humanoide Natural",
                            Foto = "https://static.jojowiki.com/images/thumb/c/c4/latest/20191015213758/Lovers_Infobox_Manga.png/400px-Lovers_Infobox_Manga.png",
                            Habilidade = "Sincronização da dor, Clones de lixo orgânico, Cultivação de brotos",
                            Name = "Lovers",
                            Parte = 3,
                            Portador = "Steely Dan",
                            Status = "Morto",
                            Tipo_Habilidade = "Longo-Alcance"
                        },
                        new
                        {
                            Id = 2,
                            Forma = "Curto-Alcance",
                            Foto = "https://static.jojowiki.com/images/thumb/2/20/latest/20191015213258/The_Hand_Infobox_Manga.png/400px-The_Hand_Infobox_Manga.png",
                            Habilidade = "Eliminação",
                            Name = "The Hand",
                            Parte = 4,
                            Portador = "Okuyasu Nijimura",
                            Status = "Vivo",
                            Tipo_Habilidade = "Humanóide artificial"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
